[package]
name = "gpv-products"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bit-vec = "0.9.1"
bitstream-io = "4.10.0"
chrono = "0.4.45"
foldhash = "0.2.0"
itertools = "0.14.0"
tinygrib2 = { git = "https://github.com/MIERUNE/tinygrib2.git", rev = "37f4ee2bca4205bf08a645be9378af1bc56ec705" }
